const assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
(async()=>{
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const dom=await JSDOM.fromURL(process.env.CONSULTATION_TEST_URL||'http://127.0.0.1:8774/consultation/?season=4',{resources:'usable',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.fetch=(u,o)=>fetch(new URL(u,w.location.href),o);w.HTMLElement.prototype.scrollIntoView=function(){};}});
 const w=dom.window,d=w.document;
 for(let i=0;i<200&&d.querySelector('#workspace').hidden;i++)await new Promise(r=>setTimeout(r,50));
 assert(!d.querySelector('#workspace').hidden);
 const click=s=>{assert(d.querySelector(s),s);d.querySelector(s).click();};
 const replace=(slot,id)=>{click('[data-open-picker="'+slot+'"]');click('[data-reset-picker]');click('[data-pick-general="'+id+'"]');};
 const select=(s,v)=>{const e=d.querySelector(s);assert(e,s);e.value=v;e.dispatchEvent(new w.Event('change',{bubbles:true}));};
 click('[data-purpose=pvp]');click('[data-general=tachibanaginchiyo]');click('[data-next]');
 assert(d.querySelector('.balance-radar'));assert.equal(d.querySelectorAll('[data-open-picker]').length,3);
 assert.equal(d.querySelectorAll('.quick-tactics .fixed-tactic').length,1);assert.equal(d.querySelectorAll('.quick-tactics [data-tactic]').length,2);
 replace(0,'hondatadakatsu');
 select('.quick-loadout [data-stat=rank]','1');assert(d.querySelector('.effect-basis').textContent.includes('剛猛Ⅱ'));
 select('.quick-tactics [data-tactic="0"]','tr004');const fireBefore=d.querySelector('.attack-power').textContent;
 select('.quick-tactics [data-tactic="0"]','tr013');assert.notEqual(d.querySelector('.attack-power').textContent,fireBefore,'healing to fire attack changes power');
 select('.quick-tactics [data-tactic="0"]','tr053');assert(d.querySelector('[data-tactic-rate=tr053]'));const beforeRate=d.querySelector('.attack-power').textContent;select('[data-tactic-rate=tr053]','40');assert.notEqual(d.querySelector('.attack-power').textContent,beforeRate);assert.equal(d.querySelector('[data-tactic-rate=tr053]').value,'40');
 select('.quick-tactics [data-tactic="0"]','tr068');assert(d.querySelector('.quick-loadout [data-stat=chishaPhysical]'));
 select('.quick-loadout [data-stat=chishaPhysical]','50');assert(d.querySelector('.balance-evidence').textContent.includes('耐久換算'));
 replace(0,'tachibanaginchiyo');
 replace(1,'tachibanadousetsu');
 click('[data-open-picker="2"]');assert(d.querySelector('[data-picker-family][aria-pressed=true]').textContent.includes('大友'));click('[data-picker-sort="武勇"]');const values=[...d.querySelectorAll('.sorted-stat b')].map(x=>Number(x.textContent));assert(values.every((v,i)=>!i||v<=values[i-1]));click('[data-close-picker]');
 assert(d.querySelector('.synergy-note').textContent.includes('立花道雪'));assert(d.querySelector('.radar-before'));
 replace(2,'houjouujiyasu');
 assert.equal(d.querySelectorAll('[data-open-picker][data-current-general]:not([data-current-general=""])').length,3);
 replace(1,'kakizakikageie');
 assert(d.querySelector('.alliance-note'));assert(d.querySelector('.leader-badge'));
 assert.equal(d.querySelector('[data-open-picker="0"]').dataset.currentGeneral,'tachibanaginchiyo');
 click('.balance-slot [data-leader=kakizakikageie]');
 assert.equal(d.querySelector('[data-open-picker="0"]').dataset.currentGeneral,'kakizakikageie');
 assert(d.querySelector('.alliance-note').textContent.includes('装備済み'));
 replace(2,'tachibanadousetsu');
 assert(!d.querySelector('.alliance-note'));assert(!d.querySelector('.leader-badge'));
 select('#season','2');click('[data-purpose=pvp]');click('[data-general=toyotomihideyoshi]');click('[data-next]');
 click('[data-open-picker="1"]');assert(!d.querySelector('[data-pick-general=tachibanaginchiyo]'));click('[data-close-picker]');
 select('#season','4');click('[data-purpose=pvp]');click('[data-general=tachibanaginchiyo]');click('[data-general=tachibanadousetsu]');click('[data-general=houjouujiyasu]');assert(d.querySelector('.balance-radar'),'third general opens results automatically');assert(!d.querySelector('#flow [data-go=counter]'));click('[data-open-picker="1"]');assert.equal(d.querySelector('[data-picker-family][aria-pressed=true]').dataset.pickerFamily,'');click('[data-picker-feature=heal]');assert(d.querySelectorAll('.picker-card').length>0);assert([...d.querySelectorAll('.picker-tags')].every(x=>x.textContent.includes('回復持ち')));const input=d.querySelector('[data-picker-query]');input.focus();input.value='忠勝';input.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.activeElement,input);assert(d.querySelector('[data-pick-general=hondatadakatsu]'));input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(!d.querySelector('.general-picker'));
 assert.deepEqual(errors,[]);dom.window.close();console.log('Balance UI: add/swap three slots, previous graph, synergy, captain change, alliance and season isolation PASS');
})().catch(e=>{console.error(e);process.exit(1)});
