const assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765/consultation/?season=4');await page.locator('#workspace').waitFor({state:'visible'});
 await page.locator('[data-purpose=pvp]').click();await page.locator('[data-general=kakizakikageie]').click();await page.locator('[data-next]').click();
 const tactic=(slot,owner='kakizakikageie')=>page.locator(`[data-tactic="${slot}"][data-owner="${owner}"]`);
 assert(await tactic(0).inputValue());assert(await tactic(1).inputValue());assert.equal(await page.locator('[data-team-mode]').inputValue(),'family');
 assert((await page.locator('.advisor-recommendations').innerText()).includes('同じ家門'));
 await page.locator('.advisor-settings>summary').click();const first=await tactic(0).inputValue();
 await page.locator('[data-stat=focus]').selectOption('intellect');assert.notEqual(await tactic(0).inputValue(),first);
 await tactic(0).selectOption('tr002');await page.locator('[data-stat=focus]').selectOption('defense');assert.equal(await tactic(0).inputValue(),'tr002');
 assert(await tactic(1).inputValue());await tactic(0).selectOption('__auto__');assert.notEqual(await tactic(0).inputValue(),'tr002');
 await page.locator('[data-team-mode]').selectOption('alliance');assert.equal(await page.locator('[data-team-mode]').inputValue(),'alliance');
 assert((await page.locator('[data-tactic]').evaluateAll(els=>els.map(e=>e.value))).includes('tr113'));
 const recId=await page.locator('[data-preview]').first().getAttribute('data-preview'),fixed=await page.locator('[data-tactic][data-owner=kakizakikageie]').evaluateAll(els=>els.map(e=>e.value));
 await page.locator('[data-preview]').first().click();assert.deepEqual(await page.locator('[data-tactic][data-owner=kakizakikageie]').evaluateAll(els=>els.map(e=>e.value)),fixed);assert(await tactic(0,recId).inputValue());
 await page.locator('[data-clear-preview]').click();await page.locator('[data-team-mode]').selectOption('family');assert(!(await page.locator('[data-tactic]').evaluateAll(els=>els.map(e=>e.value))).includes('tr113'));
 // Two different fixed families with a non-eligible leader: no invalid recommendation; reordering fixes it.
 await page.locator('[data-purpose=pvp]').click();await page.locator('[data-general=matsu]').click();await page.locator('[data-general=kakizakikageie]').click();await page.locator('[data-next]').click();
 await page.locator('[data-team-mode]').selectOption('alliance');assert.equal(await page.locator('[data-preview]').count(),0);assert((await page.locator('.advisor-recommendations .empty').innerText()).includes('大将'));
 if(!await page.locator('.advisor-settings').evaluate(e=>e.open))await page.locator('.advisor-settings>summary').click();
 await page.locator('[data-leader=kakizakikageie]').click();assert((await page.locator('[data-preview]').count())>0);
 assert((await page.locator('[data-unpin=kakizakikageie]').innerText()).includes('仮大将'));
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#advisor-root').screenshot({path:'/tmp/mobunaga-loadout-mobile.png'});await page.locator('[data-team-mode]').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/mobunaga-loadout-top.png'});
 await page.locator('#season').selectOption('1');await page.locator('[data-purpose=pvp]').click();await page.locator('[data-general=toyotomihideyoshi]').click();await page.locator('[data-next]').click();
 assert.equal(await page.locator('[data-team-mode]').inputValue(),'family');assert.equal(await page.locator('#season').inputValue(),'1');assert.equal(await page.locator('[data-team-mode] option[value=alliance]').getAttribute('disabled'),'');assert.deepEqual(errors,[]);
 console.log('Loadout UI: auto defaults, live attribute selection, manual retention, alliance equipment and family switch, consistent preview, invalid leader/reordering, mobile, season reset PASS');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
