const assert=require('node:assert/strict');
require('../consultation/core.js');require('../consultation/evidence.js');require('../consultation/advisor.js');require('../consultation/loadout.js');require('../consultation/balance.js');
const C=MobunagaConsult,A=MobunagaAdvisor;
const db=C.catalog(require('../assets/database.json'),require('../assets/s4-additions.json'),require('../assets/formations.json')),idx=C.evidenceIndex(db,4);
const blank=id=>({general:{id,name:id,family:id},martial:150,intellect:100,defense:150,normals:1,weight:1,tactics:[],effects:[],unknown:[],physicalExtra:0,magicExtra:0,healExtra:0});
const close=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);
const equip=(p,id)=>{p.tactics=[id];p.effects=[{...A.tacticModel(id),id,name:id}];};
let ps=[blank('a'),blank('b'),blank('c')];equip(ps[1],'tr064');
let a=A.analyze(ps,{turns:4,basicShare:100});
close(a.rows[0].normalShares[1],5/6);close(a.rows[0].need.reduce((s,x)=>s+x,0),200*7/12);close(a.rows[3].need.reduce((s,x)=>s+x,0),200);
ps=[blank('a'),blank('b'),blank('c')];equip(ps[0],'tr064');a=A.analyze(ps,{turns:1,basicShare:100});close(a.rows[0].normalShares[0],1/3);
close(A.analyze(ps,{turns:1,basicShare:0}).required,200);
ps=[blank('a'),blank('b')];equip(ps[1],'tr068');ps[1].chishaPhysical=50;ps[1].chishaMagic=50;
a=A.analyze(ps,{turns:4});close(a.rows[0].need.reduce((s,x)=>s+x,0),100);close(a.rows[3].need.reduce((s,x)=>s+x,0),200);close(A.analyze(ps,{turns:3}).durability,2);close(a.rows[0].physical[0],95);close(a.rows[3].physical[0],100);
ps=[blank('a'),blank('b'),blank('c')];equip(ps[1],'tr068');a=A.analyze(ps,{turns:1,physicalShare:100});close(a.required,176);ps.forEach(p=>p.intellect=200);close(A.analyze(ps,{turns:1,physicalShare:100}).required,168);
const loyal=rank=>A.analyze(['toyotomihideyoshi','hondatadakatsu','oichi'].map(id=>A.profile(idx.generals.get(id),{rank:id==='hondatadakatsu'?rank:0},idx)));
const zero=loyal(0),one=loyal(1);assert(one.actors[1].normalShare>zero.actors[1].normalShare);assert(one.actors[1].selfSustain>zero.actors[1].selfSustain);assert(one.durability>zero.durability);assert(zero.actors[1].physical>100);assert(one.profiles[1].traitAudit.some(t=>t.status==='仮定で比較'));
const g={...idx.generals.get('hondatadakatsu'),traits:[{name:'test',unlock_level:'1凸',effect:'武勇+2.5%'},{name:'unknown',unlock_level:'3凸',effect:'確率中幅上昇'}]};close(A.profile(g,{rank:1},idx).martial,A.baseStats(g).martial*1.025);close(A.profile(g,{rank:1,martial:300},idx).martial,300);assert.equal(A.profile(g,{rank:0},idx).activeTraits.length,0);assert(A.profile(g,{rank:3},idx).unknown.some(x=>x.includes('unknown')));
console.log('Tactics/ranks: taunt target/leader/expiry/type, 50% reduction=2x, chisha branch/penalty, Tadakatsu rank/counter/leech, trait unlock/unknown/manual stats PASS');
