<?php
declare(strict_types=1);
header('Cache-Control: no-store, private');
header('Pragma: no-cache');
header("Content-Security-Policy: default-src 'self'; img-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'");
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: same-origin');

require_once __DIR__ . '/../includes/analysis-session.php';

$returnUrl = mobunagaReturnUrl($_POST['next'] ?? $_GET['next'] ?? '');
if (!empty($_SESSION['authorized']) && $returnUrl !== '' && ($_SERVER['REQUEST_METHOD'] ?? '') === 'GET') {
    header('Location: '.$returnUrl, true, 303);
    exit;
}

const ADMIN_CONFIG='/var/www/.nobunaga-admin.ini';
const DB_CONFIG='/var/www/.nobunaga-db.ini';

function analysisPassphraseHash(): string
{
    if (!is_readable(ADMIN_CONFIG)) {
        return '';
    }

    $ini = parse_ini_file(ADMIN_CONFIG, true, INI_SCANNER_RAW);
    $hash = is_array($ini)
        ? (string)($ini['analysis_room']['passphrase_sha256'] ?? '')
        : '';

    return preg_match('/^[a-f0-9]{64}$/i', $hash) ? strtolower($hash) : '';
}
const INTEL_FORM_KEY='enemy_intel';
const MAX_INTEL_IMAGE_BYTES=10*1024*1024;

function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function cutText(string $v,int $max):string{$v=trim($v);return function_exists('mb_substr')?mb_substr($v,0,$max,'UTF-8'):substr($v,0,$max);}
function containsText(string $hay,string $needle):bool{if($needle==='')return true;return function_exists('mb_stripos')?mb_stripos($hay,$needle,0,'UTF-8')!==false:stripos($hay,$needle)!==false;}
function archiveDb():?PDO{if(!is_readable(DB_CONFIG))return null;$ini=parse_ini_file(DB_CONFIG,true,INI_SCANNER_RAW);$c=is_array($ini)&&isset($ini['mysql'])&&is_array($ini['mysql'])?$ini['mysql']:[];if(empty($c['database'])||empty($c['user'])||!array_key_exists('password',$c))return null;$socket=trim((string)($c['unix_socket']??''));$dsn=$socket!==''?'mysql:unix_socket='.$socket.';dbname='.$c['database'].';charset=utf8mb4':'mysql:host='.($c['host']??'localhost').';port='.($c['port']??'3306').';dbname='.$c['database'].';charset=utf8mb4';try{return new PDO($dsn,(string)$c['user'],(string)$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}catch(Throwable $e){return null;}}
function saveEnemyIntel(PDO $db):string{$enemy=cutText((string)($_POST['enemy_name']??''),120);$formation=cutText((string)($_POST['enemy_formation']??''),255);$memo=cutText((string)($_POST['intel_memo']??''),4000);$sourceUrl=cutText((string)($_POST['source_url']??''),1000);if($memo==='')return '敵情報の本文を入力してください。';if($sourceUrl!==''&&!filter_var($sourceUrl,FILTER_VALIDATE_URL))return '参照URLの形式を確認してください。';$payload=json_encode(['enemy_name'=>$enemy,'enemy_formation'=>$formation,'memo'=>$memo,'source_url'=>$sourceUrl],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($payload===false)return '投稿データを作成できません。';try{$db->beginTransaction();$st=$db->prepare("INSERT INTO form_submissions (form_key,payload_json,source_path,status) VALUES (?,CAST(? AS JSON),?,'new')");$st->execute([INTEL_FORM_KEY,$payload,'/analysis-room/']);$submissionId=(int)$db->lastInsertId();if(isset($_FILES['intel_image'])&&is_array($_FILES['intel_image'])){$file=$_FILES['intel_image'];$err=(int)($file['error']??UPLOAD_ERR_NO_FILE);if($err!==UPLOAD_ERR_NO_FILE){if($err!==UPLOAD_ERR_OK)throw new RuntimeException('画像アップロードに失敗しました。');$size=(int)($file['size']??0);if($size<1||$size>MAX_INTEL_IMAGE_BYTES)throw new RuntimeException('画像は10MB以下にしてください。');$tmp=(string)($file['tmp_name']??'');if($tmp===''||!is_uploaded_file($tmp))throw new RuntimeException('画像を確認できません。');$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=(string)$finfo->file($tmp);if(!in_array($mime,['image/jpeg','image/png','image/webp'],true))throw new RuntimeException('画像はJPG / PNG / WebPのみです。');$data=file_get_contents($tmp);if($data===false||strlen($data)!==$size)throw new RuntimeException('画像を読み込めません。');$name=cutText((string)($file['name']??'image'),255);$sha=hash('sha256',$data);$fs=$db->prepare('INSERT INTO form_submission_files (submission_id,original_name,mime_type,file_size,file_data,sha256) VALUES (?,?,?,?,?,?)');$fs->bindValue(1,$submissionId,PDO::PARAM_INT);$fs->bindValue(2,$name,PDO::PARAM_STR);$fs->bindValue(3,$mime,PDO::PARAM_STR);$fs->bindValue(4,$size,PDO::PARAM_INT);$fs->bindValue(5,$data,PDO::PARAM_LOB);$fs->bindValue(6,$sha,PDO::PARAM_STR);$fs->execute();}}$db->commit();return '';}catch(Throwable $ex){if($db->inTransaction())$db->rollBack();return $ex instanceof RuntimeException?$ex->getMessage():'敵情報を保存できませんでした。';}}
function loadEnemyIntel(PDO $db):array{try{$sql="SELECT s.id,s.payload_json,s.status,s.created_at,f.id AS file_id FROM form_submissions s LEFT JOIN form_submission_files f ON f.submission_id=s.id WHERE s.form_key=? AND s.status IN ('new','reviewed') ORDER BY FIELD(s.status,'new','reviewed'),s.id DESC LIMIT 200";$st=$db->prepare($sql);$st->execute([INTEL_FORM_KEY]);return $st->fetchAll();}catch(Throwable $e){return [];}}
function loadWatchFlags(PDO $db):array{try{$rows=$db->query("SELECT entity_key FROM enemy_watch_flags WHERE entity_type='formation' AND watch_flag=1")->fetchAll(PDO::FETCH_COLUMN);return array_fill_keys(array_map('strval',$rows),true);}catch(Throwable $e){return [];}}
function generalPortrait(string $n):?string{static $m=['北条氏康'=>'houjouujiyasu','立花道雪'=>'tachibanadousetsu','立花誾千代'=>'tachibanaginchiyo','安宅冬康'=>'atagifuyuyasu','真田昌幸'=>'sanadamasayuki','毛利元就'=>'mourimotonari','内藤昌豊'=>'naitoumasatoyo','福島正則'=>'fukushimamasanori','北条綱成'=>'houjoutsunashige','馬場信春'=>'babanobuharu','武田信玄'=>'takedashingen','飯富虎昌'=>'obutoramasa','山県昌景'=>'yamagatamasakage','山本勘助'=>'yamamotokansuke'];return isset($m[$n])?'/assets/portraits/'.$m[$n].'.webp':null;}

if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(24));
$error='';$notice='';$action=is_string($_POST['action']??null)?$_POST['action']:'';$csrf=is_string($_POST['csrf']??null)?$_POST['csrf']:'';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals((string)$_SESSION['csrf'],$csrf)){http_response_code(403);$error='画面を読み直して、もう一度お試しください。';}
 elseif($action==='logout'){$_SESSION=[];session_regenerate_id(true);mobunagaAuthCookie(0);$_SESSION['csrf']=bin2hex(random_bytes(24));}
 elseif($action==='login'){$lockedUntil=(int)($_SESSION['locked_until']??0);if($lockedUntil>time())$error='試行回数が多いため、少し待ってからお試しください。';else{$passphrase=is_string($_POST['passphrase']??null)?trim($_POST['passphrase']):'';if(($expectedHash=analysisPassphraseHash())!==''&&hash_equals($expectedHash,hash('sha256',$passphrase))){mobunagaAuthorize();$_SESSION['attempts']=0;$_SESSION['csrf']=bin2hex(random_bytes(24));if($returnUrl!==''){header('Location: '.$returnUrl,true,303);exit;}}else{$attempts=(int)($_SESSION['attempts']??0)+1;$_SESSION['attempts']=$attempts;if($attempts>=5){$_SESSION['attempts']=0;$_SESSION['locked_until']=time()+60;}$error='合言葉が違います。';}}}
 elseif(!empty($_SESSION['authorized'])&&$action==='submit_enemy_intel'){$db=archiveDb();if(!$db)$error='DBへ接続できません。';else{$error=saveEnemyIntel($db);if($error==='')$notice='敵情報を蓄積しました。';}}
 elseif(!empty($_SESSION['authorized'])&&$action==='mark_enemy_intel_reviewed'){$db=archiveDb();$id=(int)($_POST['intel_id']??0);if(!$db||$id<1)$error='処理済み更新に失敗しました。';else try{$st=$db->prepare("UPDATE form_submissions SET status='reviewed' WHERE id=? AND form_key=? AND status='new'");$st->execute([$id,INTEL_FORM_KEY]);$notice=$st->rowCount()?'処理済みにしました。':'対象はすでに処理済みです。';}catch(Throwable $e){$error='処理済み更新に失敗しました。';}}
 elseif(!empty($_SESSION['authorized'])&&$action==='toggle_watch'){$db=archiveDb();$fid=cutText((string)($_POST['formation_id']??''),190);if(!$db||$fid==='')$error='要注意フラグを更新できません。';else try{$current=(int)($_POST['watch_flag']??0);if($current===1){$st=$db->prepare("INSERT INTO enemy_watch_flags(entity_type,entity_key,watch_flag) VALUES('formation',?,1) ON DUPLICATE KEY UPDATE watch_flag=1");$st->execute([$fid]);$notice='要注意にしました。';}else{$st=$db->prepare("DELETE FROM enemy_watch_flags WHERE entity_type='formation' AND entity_key=?");$st->execute([$fid]);$notice='要注意を解除しました。';}}catch(Throwable $e){$error='要注意フラグDBを準備してください。';}}
}

$authorized=!empty($_SESSION['authorized']);$csrfToken=e((string)$_SESSION['csrf']);$archiveData=[];$intelRows=[];$watchFlags=[];$dbReady=false;
if($authorized){define('MOBUNAGA_ANALYSIS_ROOM',true);$archiveData=require __DIR__.'/enemy-observations.php';$db=archiveDb();if($db){$dbReady=true;$intelRows=loadEnemyIntel($db);$watchFlags=loadWatchFlags($db);}}
$q=cutText((string)($_GET['q']??''),100);$watchOnly=(string)($_GET['watch']??'')==='1';
$allFormations=$archiveData['formations']??[];$suggestions=[];$filteredFormations=[];
foreach($allFormations as $formation){foreach(($formation['members']??[]) as $m)$suggestions[]=(string)$m;foreach(($formation['observations']??[]) as $o)$suggestions[]=(string)($o['opponent']??'');$fid=(string)($formation['id']??'');$hay=implode(' ',array_map('strval',$formation['members']??[])).' '.(string)($formation['summary']??'');foreach(($formation['observations']??[]) as $o)$hay.=' '.(string)($o['opponent']??'');$isWatch=!empty($watchFlags[$fid]);if(($q===''||containsText($hay,$q))&&(!$watchOnly||$isWatch))$filteredFormations[]=$formation;}
$suggestions=array_values(array_unique(array_filter($suggestions,fn($v)=>$v!=='')));sort($suggestions,SORT_NATURAL|SORT_FLAG_CASE);
usort($filteredFormations,function($a,$b)use($watchFlags){$aw=!empty($watchFlags[(string)($a['id']??'')]);$bw=!empty($watchFlags[(string)($b['id']??'')]);if($aw!==$bw)return $bw<=>$aw;return ((int)($b['attention_score']??0))<=>((int)($a['attention_score']??0));});
?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#173f49"><meta name="robots" content="noindex,nofollow,noarchive"><title>分析班資料館｜モブナガの軍議戦略サイト</title><link rel="icon" href="/assets/crest.svg?v=20260923-archive2" type="image/svg+xml"><link rel="stylesheet" href="/assets/analysis-room.css?v=20260923-archive2"><link rel="stylesheet" href="/assets/analysis-room-v2.css?v=20260923-archive2"><link rel="stylesheet" href="/assets/formation-community.css?v=20260923-community1"><script src="/assets/formation-community.js?v=20260923-community1" defer></script></head>
<body><header class="archive-header"><a class="brand" href="/"><span class="brand-face mobunaga-face" aria-hidden="true"><img src="/assets/mobunaga.png?v=20260923-archive2" alt=""></span><span>モブナガの軍議戦略サイト<small>信長の野望 真戦</small></span></a><a class="back-link" href="/">軍議の間へ戻る</a></header><main><section class="archive-card<?=$authorized?' archive-card-wide':''?>" aria-labelledby="archive-title"><p class="eyebrow">CONFIDENTIAL ARCHIVE</p><h1 id="archive-title">分析班資料館</h1>
<?php if($authorized): ?><div class="flash" aria-hidden="true"></div><p class="status-mark">入館済</p><h2>敵編成・実戦観測記録</h2><p class="description">敵名・武将名で素早く絞り込み、要注意対象を上に固定できます。</p>
<section class="intel-panel" aria-labelledby="intel-title"><div class="intel-panel-head"><div><p class="eyebrow">INTELLIGENCE INBOX</p><h3 id="intel-title">敵情報投稿</h3></div><div class="intel-count"><strong><?=count(array_filter($intelRows,fn($r)=>($r['status']??'')==='new'))?></strong><span>未処理</span></div></div><p class="intel-help">投稿フォームは普段は閉じています。必要な時だけ開いて、戦報・敵編成・挙動を蓄積してください。</p><?php if($notice!==''):?><p class="notice" role="status"><?=e($notice)?></p><?php endif;?><?php if($error!==''):?><p class="error intel-error" role="alert"><?=e($error)?></p><?php endif;?><?php if(!$dbReady):?><p class="error intel-error">DBへ接続できないため、現在は投稿を保存できません。</p><?php else:?><details class="intel-compose"<?=$error!==''?' open':''?>><summary>＋ 敵情報を投稿</summary><form class="intel-form" method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="submit_enemy_intel"><input type="hidden" name="csrf" value="<?=$csrfToken?>"><div class="intel-fields"><label>敵名・プレイヤー名<input type="text" name="enemy_name" maxlength="120" placeholder="任意"></label><label>編成・武将<input type="text" name="enemy_formation" maxlength="255" placeholder="例：徳川家康・本多忠勝・本多正信"></label></div><label>敵情報<textarea name="intel_memo" maxlength="4000" required placeholder="例：家康隊。知略が低いので計略攻撃が刺さる。"></textarea></label><div class="intel-fields"><label>参照URL<input type="url" name="source_url" maxlength="1000" placeholder="任意"></label><label>画像<input type="file" name="intel_image" accept="image/jpeg,image/png,image/webp"></label></div><button type="submit">敵情報を蓄積する</button></form></details><?php endif;?>
<?php if($intelRows):?><div class="intel-queue"><h4>蓄積済み情報</h4><?php foreach($intelRows as $row):$p=json_decode((string)$row['payload_json'],true);if(!is_array($p))$p=[];$isNew=($row['status']??'')==='new';?><article class="intel-item <?=$isNew?'is-new':'is-reviewed'?>"><div class="intel-item-head"><strong>#<?=(int)$row['id']?> <?=e((string)($p['enemy_name']??''))?></strong><span class="intel-status"><?=$isNew?'未処理':'済み'?></span></div><?php if(!empty($p['enemy_formation'])):?><p class="intel-formation"><?=e((string)$p['enemy_formation'])?></p><?php endif;?><p class="intel-memo"><?=nl2br(e((string)($p['memo']??'')))?></p><div class="intel-meta"><time><?=e((string)$row['created_at'])?></time><?php if(!empty($p['source_url'])):?><a href="<?=e((string)$p['source_url'])?>" target="_blank" rel="noopener noreferrer">参照URL</a><?php endif;?><?php if(!empty($row['file_id'])):?><a href="/analysis-room/intel-image.php?id=<?=(int)$row['file_id']?>" target="_blank" rel="noopener noreferrer">添付画像</a><?php endif;?></div><?php if($isNew):?><form method="post" class="intel-done-form"><input type="hidden" name="action" value="mark_enemy_intel_reviewed"><input type="hidden" name="csrf" value="<?=$csrfToken?>"><input type="hidden" name="intel_id" value="<?=(int)$row['id']?>"><button type="submit" class="intel-done">済みにする</button></form><?php endif;?></article><?php endforeach;?></div><?php endif;?></section>

<form class="archive-search" method="get" role="search"><input type="search" name="q" value="<?=e($q)?>" list="enemy-search-options" placeholder="敵名・武将名を入力"><datalist id="enemy-search-options"><?php foreach($suggestions as $s):?><option value="<?=e($s)?>"></option><?php endforeach;?></datalist><select name="watch" aria-label="要注意で絞り込み"><option value="">すべて</option><option value="1"<?=$watchOnly?' selected':''?>>要注意のみ</option></select><button type="submit">検索</button></form><p class="search-hint">候補から敵名・武将名を選ぶだけでも絞り込めます。要注意フラグ付きは常に上へ表示します。</p>
<section class="source-panel"><h3>資料情報</h3><dl><div><dt>動画撮影日時</dt><dd><?=e((string)$archiveData['source']['captured_at'])?></dd></div><div><dt>分析更新日</dt><dd><?=e((string)$archiveData['updated_at'])?></dd></div><div><dt>動画時間</dt><dd><?=e((string)$archiveData['source']['duration'])?></dd></div><div><dt>登録編成</dt><dd><?=count($allFormations)?>系統</dd></div></dl><p><?=e((string)$archiveData['source']['analyst_note'])?></p></section>
<div class="formation-grid"><?php if(!$filteredFormations):?><p class="archive-empty">該当する敵資料がありません。</p><?php endif;?><?php foreach($filteredFormations as $formation):$score=(int)$formation['attention_score'];$scoreClass=$score>=65?'danger':($score>=60?'warning':'normal');$fid=(string)($formation['id']??'');$isWatch=!empty($watchFlags[$fid]);?><article class="enemy-card<?=$isWatch?' is-watch':''?>"><div class="enemy-card-head"><div><p class="formation-label">確認 <?=count($formation['observations'])?>戦 ／ 確度 <?=e((string)$formation['confidence'])?><?=$isWatch?'<span class="watch-badge">要注意</span>':''?></p><div class="enemy-members"><?php foreach($formation['members'] as $member):$portrait=generalPortrait((string)$member);?><span class="enemy-member"><?php if($portrait):?><img src="<?=e($portrait)?>" alt="" width="58" height="58" loading="lazy"><?php endif;?><strong><?=e((string)$member)?></strong></span><?php endforeach;?></div></div><div class="enemy-card-head-actions"><form method="post"><input type="hidden" name="action" value="toggle_watch"><input type="hidden" name="csrf" value="<?=$csrfToken?>"><input type="hidden" name="formation_id" value="<?=e($fid)?>"><input type="hidden" name="watch_flag" value="<?=$isWatch?'0':'1'?>"><button type="submit" class="watch-toggle<?=$isWatch?' on':''?>"><?=$isWatch?'★ 要注意':'☆ 要注意'?></button></form><div class="attention <?=$scoreClass?>"><span>要注意度</span><strong><?=$score?></strong><small>偏差値</small></div></div></div><p class="enemy-summary"><?=e((string)$formation['summary'])?></p><div class="watch-list"><h4>要注意ポイント</h4><ul><?php foreach($formation['watch_points'] as $point):?><li><?=e((string)$point)?></li><?php endforeach;?></ul></div><div class="observation-table-wrap"><table><thead><tr><th>対戦日時</th><th>相手</th><th>結果</th><th>動画位置</th></tr></thead><tbody><?php foreach($formation['observations'] as $o):?><tr><td><?=e((string)$o['battle_at'])?></td><td><?=e((string)$o['opponent'])?></td><td><span class="result result-<?=e((string)$o['result'])?>"><?=e((string)$o['result'])?></span></td><td><?=e((string)$o['video_at'])?></td></tr><?php endforeach;?></tbody></table></div><div data-community-mount="<?=e($fid)?>"></div></article><?php endforeach;?></div>
<form method="post"><input type="hidden" name="action" value="logout"><input type="hidden" name="csrf" value="<?=$csrfToken?>"><button class="secondary" type="submit">資料館から退出する</button></form>
<?php else:?><p class="description">この先は分析班専用です。合言葉を入力してください。</p><?php if($error!==''):?><p class="error" role="alert"><?=e($error)?></p><?php endif;?><form class="login-form" method="post" autocomplete="off"><input type="hidden" name="action" value="login"><input type="hidden" name="next" value="<?=e($returnUrl)?>"><input type="hidden" name="csrf" value="<?=$csrfToken?>"><label for="passphrase">合言葉</label><input id="passphrase" name="passphrase" type="text" inputmode="text" lang="ja" required maxlength="80" autofocus autocapitalize="off" spellcheck="false"><button type="submit">入館する</button></form><?php endif;?></section></main><footer>モブナガの軍議戦略サイト ／ 分析班資料館</footer></body></html>
