<?php
declare(strict_types=1);
header('Cache-Control: no-store, private');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: same-origin');
header("Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'");
const DB_CONFIG='/var/www/.nobunaga-db.ini';
session_name('mobunaga_admin');
session_set_cookie_params(['lifetime'=>0,'path'=>'/admin/','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Strict']);
session_start();
if(empty($_SESSION['authorized'])){header('Location:/admin/');exit;}
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function db():PDO{if(!is_readable(DB_CONFIG))throw new RuntimeException('DB設定がありません');$i=parse_ini_file(DB_CONFIG,true,INI_SCANNER_RAW);$c=$i['mysql']??[];$sock=trim((string)($c['unix_socket']??''));$dsn=$sock!==''?'mysql:unix_socket='.$sock.';dbname='.$c['database'].';charset=utf8mb4':'mysql:host='.($c['host']??'localhost').';port='.($c['port']??'3306').';dbname='.$c['database'].';charset=utf8mb4';return new PDO($dsn,(string)$c['user'],(string)$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}
$msg='';$err='';
try{$pdo=db();if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals((string)$_SESSION['csrf'],(string)($_POST['csrf']??'')))throw new RuntimeException('画面を再読込してください');$id=(int)($_POST['id']??0);$action=(string)($_POST['action']??'');$map=['approve'=>'approved','reject'=>'rejected','delete'=>'deleted'];if($id<1||!isset($map[$action]))throw new RuntimeException('操作が不正です');$s=$pdo->prepare('UPDATE content_comments SET status=?,reviewed_at=NOW() WHERE id=?');$s->execute([$map[$action],$id]);$msg='更新しました。';}$status=(string)($_GET['status']??'pending');if(!in_array($status,['pending','approved','rejected','deleted'],true))$status='pending';$s=$pdo->prepare('SELECT id,entity_type,entity_id,season_no,poster_name,comment_text,status,created_at FROM content_comments WHERE status=? ORDER BY season_no DESC,id DESC LIMIT 300');$s->execute([$status]);$rows=$s->fetchAll();$pending=(int)$pdo->query("SELECT COUNT(*) FROM content_comments WHERE status='pending'")->fetchColumn();}catch(Throwable $x){$err=$x->getMessage();$rows=[];$pending=0;$status='pending';}
$csrf=e((string)$_SESSION['csrf']);
?><!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>コメント承認｜モブナガ管理者</title><style>body{margin:0;background:#eef2f5;color:#20313a;font-family:system-ui,sans-serif}header{background:#173f49;color:#fff;padding:18px 24px}main{max-width:1100px;margin:auto;padding:20px}.bar,.card{background:#fff;border:1px solid #ccd6dc;border-radius:12px;padding:16px;margin-bottom:14px}.bar{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.tabs{display:flex;gap:8px;flex-wrap:wrap}.tabs a{padding:8px 11px;border-radius:8px;background:#e8eef1;color:#173f49;text-decoration:none;font-weight:700}.tabs a.on{background:#175b72;color:#fff}.meta{font-size:12px;color:#65727a}.season-badge{display:inline-block;padding:2px 7px;border-radius:999px;background:#173f49;color:#fff;font-weight:800;margin-right:6px}.comment{white-space:pre-wrap;line-height:1.7}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}button{border:0;border-radius:8px;padding:9px 12px;color:white;background:#175b72;font-weight:800}.reject{background:#9b6a23}.delete{background:#9a3f3f}.msg{padding:10px;background:#dff3e6}.err{padding:10px;background:#ffe2e2}</style></head><body><header><strong>モブナガ 管理者ページ ／ コメント承認</strong></header><main><section class="bar"><div><h1 style="margin:0">コメント承認</h1><p class="meta">承認待ち <?=$pending?> 件 ／ コメントは投稿者のシーズンを保持します</p></div><a href="/admin/">戦法管理へ戻る</a></section><nav class="bar tabs"><?php foreach(['pending'=>'承認待ち','approved'=>'承認済み','rejected'=>'却下','deleted'=>'削除'] as $k=>$v):?><a class="<?=$status===$k?'on':''?>" href="?status=<?=$k?>"><?=$v?></a><?php endforeach;?></nav><?php if($msg):?><p class="msg"><?=e($msg)?></p><?php endif;?><?php if($err):?><p class="err"><?=e($err)?></p><?php endif;?><?php foreach($rows as $r):?><article class="card"><div class="meta"><span class="season-badge">S<?=(int)$r['season_no']?></span>#<?=(int)$r['id']?> ／ <?=e((string)$r['entity_type'])?>: <?=e((string)$r['entity_id'])?> ／ <?=e((string)$r['created_at'])?></div><h3><?=e((string)$r['poster_name'])?></h3><p class="comment"><?=e((string)$r['comment_text'])?></p><form class="actions" method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><?php if($status!=='approved'):?><button name="action" value="approve">承認</button><?php endif;?><?php if($status!=='rejected'):?><button class="reject" name="action" value="reject">却下</button><?php endif;?><button class="delete" name="action" value="delete">削除</button></form></article><?php endforeach;?><?php if(!$rows&&!$err):?><p class="card">該当コメントはありません。</p><?php endif;?></main></body></html>