<?php
declare(strict_types=1);
header('Cache-Control: no-store, private');
header('Pragma: no-cache');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: same-origin');
header("Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'");
const ADMIN_CONFIG='/var/www/.nobunaga-admin.ini';
const DB_CONFIG='/var/www/.nobunaga-db.ini';
const PUBLIC_DB_JSON=__DIR__.'/../assets/database.json';
session_name('mobunaga_admin');
session_set_cookie_params(['lifetime'=>0,'path'=>'/admin/','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Strict']);
session_start();
if(empty($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(32));
function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function cut(string $v,int $n):string{return function_exists('mb_substr')?mb_substr($v,0,$n,'UTF-8'):substr($v,0,$n);}
function adminCfg():array{if(!is_readable(ADMIN_CONFIG))throw new RuntimeException('管理者設定が未登録です');$i=parse_ini_file(ADMIN_CONFIG,true,INI_SCANNER_RAW);$c=$i['admin']??[];if(empty($c['id'])||empty($c['password_hash']))throw new RuntimeException('管理者設定が不完全です');return $c;}
function db():PDO{if(!is_readable(DB_CONFIG))throw new RuntimeException('DB設定が未登録です');$i=parse_ini_file(DB_CONFIG,true,INI_SCANNER_RAW);$c=$i['mysql']??[];$sock=trim((string)($c['unix_socket']??''));$dsn=$sock!==''?'mysql:unix_socket='.$sock.';dbname='.$c['database'].';charset=utf8mb4':'mysql:host='.($c['host']??'localhost').';port='.($c['port']??'3306').';dbname='.$c['database'].';charset=utf8mb4';return new PDO($dsn,(string)$c['user'],(string)$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}
function catalog():array{$d=json_decode((string)file_get_contents(PUBLIC_DB_JSON),true,512,JSON_THROW_ON_ERROR);return is_array($d['tactics']??null)?$d['tactics']:[];}
function nf(string $k):?float{$v=$_POST[$k]??'';if(!is_string($v)||trim($v)==='')return null;if(!is_numeric($v))throw new RuntimeException($k.' は数値で入力してください');return (float)$v;}
function flag(string $k):?int{$v=$_POST[$k]??'auto';return $v==='1'?1:($v==='0'?0:null);}
function flagSelect(string $name,$v):string{$cur=$v===null?'auto':(string)(int)$v;$o='<select name="'.e($name).'">';foreach(['auto'=>'自動判定','1'=>'あり','0'=>'なし'] as $k=>$l)$o.='<option value="'.$k.'"'.($cur===$k?' selected':'').'>'.$l.'</option>';return $o.'</select>';}
function ensureBase(PDO $db,array $t):void{$src=is_array($t['source']??null)?$t['source']:[];$sid=(string)($t['source_id']??($src['id']??''));if($sid==='')$sid='static-'.$t['id'];$sp=$db->prepare('INSERT INTO source_pages (id,source_url,local_path,sha256,fetched_at,source_updated,title) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=id');$sp->execute([$sid,(string)($src['source_url']??''),(string)($src['local_path']??''),(string)($src['sha256']??str_repeat('0',64)),(string)($src['fetched_at']??date(DATE_ATOM)),$src['source_updated']??null,$src['title']??null]);$st=$db->prepare('INSERT INTO tactics (id,name,`rank`,category,activation_rate,effect,first_season,applicable_troop,acquisition,source_id) VALUES (?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),`rank`=VALUES(`rank`),category=VALUES(category),activation_rate=VALUES(activation_rate),first_season=VALUES(first_season),applicable_troop=VALUES(applicable_troop),acquisition=VALUES(acquisition),source_id=VALUES(source_id)');$st->execute([(string)$t['id'],(string)($t['name']??''),$t['rank']??null,$t['category']??null,$t['activation_rate']??null,$t['effect']??null,$t['first_season']??null,$t['applicable_troop']??null,$t['acquisition']??null,$sid]);}
$statusMap=['confusion'=>'混乱','disarm'=>'封撃','silence'=>'無策','weakness'=>'虚弱','taunt'=>'挑発','flee'=>'逃亡','panic'=>'恐慌','burn'=>'燃焼','poison'=>'中毒','paralysis'=>'麻痺','heal_block'=>'禁療','stun'=>'震撼'];
$error='';$msg='';$action=is_string($_POST['action']??null)?$_POST['action']:'';$csrf=is_string($_POST['csrf']??null)?$_POST['csrf']:'';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals((string)$_SESSION['csrf'],$csrf)){http_response_code(403);$error='画面を再読み込みしてください。';}
 elseif($action==='login'){try{$c=adminCfg();$id=trim((string)($_POST['admin_id']??''));$pw=(string)($_POST['password']??'');if(hash_equals((string)$c['id'],$id)&&password_verify($pw,(string)$c['password_hash'])){session_regenerate_id(true);$_SESSION['authorized']=true;$_SESSION['csrf']=bin2hex(random_bytes(32));}else$error='IDまたはパスワードが違います。';}catch(Throwable $x){$error=$x->getMessage();}}
 elseif($action==='logout'){$_SESSION=[];session_regenerate_id(true);$_SESSION['csrf']=bin2hex(random_bytes(32));}
}
$authorized=!empty($_SESSION['authorized']);$pdo=null;$cat=[];$dbRows=[];$statusRows=[];$dbCount=0;
if($authorized){try{$pdo=db();$cat=catalog();$dbCount=(int)$pdo->query('SELECT COUNT(*) FROM tactics')->fetchColumn();foreach($pdo->query('SELECT * FROM tactics')->fetchAll() as $r)$dbRows[(string)$r['id']]=$r;foreach($pdo->query('SELECT * FROM tactic_status_effects ORDER BY tactic_id,sort_order,id')->fetchAll() as $s)$statusRows[(string)$s['tactic_id']][(string)$s['status_code']]=$s;}catch(Throwable $x){$error=$x->getMessage();}}
if($authorized&&$pdo&&$_SERVER['REQUEST_METHOD']==='POST'&&$action==='save'&&$error===''){
 try{$id=trim((string)($_POST['id']??''));$base=null;foreach($cat as $c)if((string)($c['id']??'')===$id){$base=$c;break;}if(!$base)throw new RuntimeException('戦法IDが不正です');$pdo->beginTransaction();ensureBase($pdo,$base);
 $effect=cut(trim((string)($_POST['effect']??'')),4000);$note=cut(trim((string)($_POST['metric_note']??'')),255);$activation=nf('activation_probability');if($activation!==null&&($activation<0||$activation>100))throw new RuntimeException('発動率(Lv10)は0〜100%で入力してください');
 $st=$pdo->prepare('UPDATE tactics SET effect=?,activation_probability=?,damage_rate=?,damage_rate_min=?,damage_rate_max=?,damage_expected=?,damage_upper=?,damage_lower=?,heal_rate=?,heal_rate_min=?,heal_rate_max=?,heal_expected=?,heal_upper=?,heal_lower=?,lifesteal_rate=?,mind_attack_rate=?,flag_damage=?,flag_heal=?,flag_buff=?,flag_debuff=?,flag_control=?,flag_special=?,flag_lifesteal=?,flag_mind_attack=?,metric_note=?,metric_updated_at=NOW() WHERE id=?');
 $st->execute([$effect,$activation,nf('damage_rate'),nf('damage_rate_min'),nf('damage_rate_max'),nf('damage_expected'),nf('damage_upper'),nf('damage_lower'),nf('heal_rate'),nf('heal_rate_min'),nf('heal_rate_max'),nf('heal_expected'),nf('heal_upper'),nf('heal_lower'),nf('lifesteal_rate'),nf('mind_attack_rate'),flag('flag_damage'),flag('flag_heal'),flag('flag_buff'),flag('flag_debuff'),flag('flag_control'),flag('flag_special'),flag('flag_lifesteal'),flag('flag_mind_attack'),$note===''?null:$note,$id]);
 $del=$pdo->prepare('DELETE FROM tactic_status_effects WHERE tactic_id=?');$del->execute([$id]);$ins=$pdo->prepare('INSERT INTO tactic_status_effects (tactic_id,status_code,status_name,enabled,probability_pct,duration_turns,target_scope,target_count,trigger_condition,notes,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?,?)');$order=0;
 foreach($statusMap as $code=>$name){$enabled=isset($_POST['status_'.$code])?1:0;$prob=nf('prob_'.$code);$dur=nf('dur_'.$code);$target=cut(trim((string)($_POST['target_'.$code]??'')),64);if($enabled||$prob!==null||$dur!==null||$target!=='')$ins->execute([$id,$code,$name,$enabled,$prob,$dur,$target===''?null:$target,null,null,null,$order++]);}
 $pdo->commit();$msg='保存しました。発動率(Lv10)・数値効果・状態異常をMySQLへ反映しました。';$dbRows=[];foreach($pdo->query('SELECT * FROM tactics')->fetchAll() as $r)$dbRows[(string)$r['id']]=$r;$statusRows=[];foreach($pdo->query('SELECT * FROM tactic_status_effects ORDER BY tactic_id,sort_order,id')->fetchAll() as $s)$statusRows[(string)$s['tactic_id']][(string)$s['status_code']]=$s;
 }catch(Throwable $x){if($pdo&&$pdo->inTransaction())$pdo->rollBack();$error=$x->getMessage();}}
$q=cut(trim((string)($_GET['q']??'')),100);$statusFilter=(string)($_GET['status']??'');$rows=[];
if($authorized&&$pdo){foreach($cat as $base){$id=(string)($base['id']??'');$r=array_merge($base,$dbRows[$id]??[]);if($q!==''&&!str_contains((string)($r['name']??''),$q)&&!str_contains((string)($r['effect']??''),$q))continue;if($statusFilter!==''&&empty($statusRows[$id][$statusFilter]['enabled']))continue;$rows[]=$r;}usort($rows,fn($a,$b)=>strcmp((string)$a['name'],(string)$b['name']));}
$csrfToken=e((string)$_SESSION['csrf']);
?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>モブナガ管理者</title><style>
:root{--bg:#eef2f5;--card:#fff;--line:#ccd6dc;--ink:#20313a;--nav:#173f49;--accent:#175b72}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:system-ui,-apple-system,"Segoe UI",sans-serif}header{background:var(--nav);color:#fff;padding:18px 24px}main{max-width:1600px;margin:auto;padding:20px}.panel{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px;margin-bottom:16px}.login{max-width:460px;margin:70px auto}.login input,.search input,.search select,textarea,.metrics input,.flags select,.statusgrid input{width:100%;padding:8px;border:1px solid #bbc8cf;border-radius:7px}.search{display:grid;grid-template-columns:1fr 220px auto;gap:8px}.row{display:grid;grid-template-columns:210px 1fr;gap:18px}.name{font-size:18px;font-weight:800}.meta{font-size:12px;color:#667}.flags{display:grid;grid-template-columns:repeat(8,minmax(105px,1fr));gap:8px;margin:10px 0}.flags label,.metrics label,.statusgrid label{font-size:12px;font-weight:700}.metrics{display:grid;grid-template-columns:repeat(5,minmax(110px,1fr));gap:8px;margin:10px 0}.statusgrid{display:grid;grid-template-columns:repeat(4,minmax(220px,1fr));gap:10px;margin:12px 0}.statusbox{padding:10px;border:1px solid #d4dde2;border-radius:8px;background:#f8fafb}.statushead{display:flex;gap:8px;align-items:center;margin-bottom:8px}.statushead input{width:auto}.statusfields{display:grid;grid-template-columns:1fr 1fr;gap:6px}.statusfields .wide{grid-column:1/-1}textarea{min-height:92px}button{border:0;border-radius:8px;background:var(--accent);color:white;padding:10px 14px;font-weight:800;cursor:pointer}.bar{display:flex;gap:10px;align-items:center;justify-content:space-between;flex-wrap:wrap}.barlinks{display:flex;gap:8px;align-items:center}.barlinks a{padding:9px 12px;border-radius:8px;background:#e8eef1;color:#173f49;text-decoration:none;font-weight:800}.msg{background:#dff3e6;padding:10px;border-radius:8px}.err{background:#ffe2e2;padding:10px;border-radius:8px}.savebar{text-align:right;margin-top:10px}h3{margin:16px 0 6px}.lv10{background:#fff8d9!important;border-color:#d6bb61!important;font-weight:800}@media(max-width:1000px){.row{grid-template-columns:1fr}.flags,.metrics,.statusgrid{grid-template-columns:repeat(2,1fr)}.search{grid-template-columns:1fr}}@media(max-width:620px){.flags,.metrics,.statusgrid{grid-template-columns:1fr}}
</style></head><body><header><strong>モブナガ 管理者ページ</strong></header><main>
<?php if(!$authorized):?><section class="panel login"><h1>管理者ログイン</h1><?php if($error):?><p class="err"><?=e($error)?></p><?php endif;?><form method="post"><input type="hidden" name="action" value="login"><input type="hidden" name="csrf" value="<?=$csrfToken?>"><label>管理者ID<input name="admin_id" required></label><label>パスワード<input name="password" type="password" required></label><button>ログイン</button></form></section><?php else:?>
<div class="panel bar"><div><h1 style="margin:0">戦法データ修正</h1><p class="meta">公開データ <?=count($cat)?>件 ／ MySQL登録 <?=$dbCount?>件。数値は原則すべてLv10基準で管理します。</p></div><div class="barlinks"><a href="/admin/comments.php">コメント承認</a><form method="post"><input type="hidden" name="action" value="logout"><input type="hidden" name="csrf" value="<?=$csrfToken?>"><button>ログアウト</button></form></div></div>
<div class="panel"><form class="search" method="get"><input name="q" value="<?=e($q)?>" placeholder="戦法名・効果文で検索"><select name="status"><option value="">状態異常すべて</option><?php foreach($statusMap as $c=>$n):?><option value="<?=e($c)?>"<?=$statusFilter===$c?' selected':''?>><?=e($n)?>付与</option><?php endforeach;?></select><button>検索</button></form></div>
<?php if($msg):?><p class="msg"><?=e($msg)?></p><?php endif;?><?php if($error):?><p class="err"><?=e($error)?></p><?php endif;?>
<?php foreach($rows as $r):$id=(string)$r['id'];$sr=$statusRows[$id]??[];?><form class="panel row" method="post"><div><div class="name"><?=e((string)$r['name'])?></div><div class="meta">ID: <?=e($id)?><br>種別: <?=e((string)($r['category']??''))?><br>元表記: <?=e((string)($r['activation_rate']??''))?><br>発動率(Lv10): <?=($r['activation_probability']??null)!==null?e((string)$r['activation_probability']).'%':'未入力'?><br><?=isset($dbRows[$id])?'MySQL登録済':'公開JSONのみ'?></div></div><div><input type="hidden" name="action" value="save"><input type="hidden" name="csrf" value="<?=$csrfToken?>"><input type="hidden" name="id" value="<?=e($id)?>">
<div class="flags"><label>ダメージ<?=flagSelect('flag_damage',$r['flag_damage']??null)?></label><label>回復<?=flagSelect('flag_heal',$r['flag_heal']??null)?></label><label>強化<?=flagSelect('flag_buff',$r['flag_buff']??null)?></label><label>弱体<?=flagSelect('flag_debuff',$r['flag_debuff']??null)?></label><label>制御<?=flagSelect('flag_control',$r['flag_control']??null)?></label><label>特殊<?=flagSelect('flag_special',$r['flag_special']??null)?></label><label>離反<?=flagSelect('flag_lifesteal',$r['flag_lifesteal']??null)?></label><label>心攻<?=flagSelect('flag_mind_attack',$r['flag_mind_attack']??null)?></label></div>
<label>効果文<textarea name="effect"><?=e((string)($r['effect']??''))?></textarea></label>
<h3>数値効果（Lv10基準）</h3><div class="metrics"><label>発動率(Lv10)%<input class="lv10" name="activation_probability" type="number" min="0" max="100" step="0.001" value="<?=e((string)($r['activation_probability']??''))?>"></label><label>ダメ倍率<input name="damage_rate" value="<?=e((string)($r['damage_rate']??''))?>"></label><label>ダメ最小%<input name="damage_rate_min" value="<?=e((string)($r['damage_rate_min']??''))?>"></label><label>ダメ最大%<input name="damage_rate_max" value="<?=e((string)($r['damage_rate_max']??''))?>"></label><label>ダメ期待<input name="damage_expected" value="<?=e((string)($r['damage_expected']??''))?>"></label><label>ダメ上振れ<input name="damage_upper" value="<?=e((string)($r['damage_upper']??''))?>"></label><label>ダメ下振れ<input name="damage_lower" value="<?=e((string)($r['damage_lower']??''))?>"></label><label>回復倍率<input name="heal_rate" value="<?=e((string)($r['heal_rate']??''))?>"></label><label>回復最小%<input name="heal_rate_min" value="<?=e((string)($r['heal_rate_min']??''))?>"></label><label>回復最大%<input name="heal_rate_max" value="<?=e((string)($r['heal_rate_max']??''))?>"></label><label>回復期待<input name="heal_expected" value="<?=e((string)($r['heal_expected']??''))?>"></label><label>回復上振れ<input name="heal_upper" value="<?=e((string)($r['heal_upper']??''))?>"></label><label>回復下振れ<input name="heal_lower" value="<?=e((string)($r['heal_lower']??''))?>"></label><label>離反率%<input name="lifesteal_rate" value="<?=e((string)($r['lifesteal_rate']??''))?>"></label><label>心攻率%<input name="mind_attack_rate" value="<?=e((string)($r['mind_attack_rate']??''))?>"></label></div>
<h3>状態異常付与</h3><div class="statusgrid"><?php foreach($statusMap as $code=>$name):$s=$sr[$code]??[];?><div class="statusbox"><label class="statushead"><input type="checkbox" name="status_<?=e($code)?>" value="1"<?=!empty($s['enabled'])?' checked':''?>><?=e($name)?></label><div class="statusfields"><label>確率%<input name="prob_<?=e($code)?>" value="<?=e((string)($s['probability_pct']??''))?>"></label><label>継続T<input name="dur_<?=e($code)?>" value="<?=e((string)($s['duration_turns']??''))?>"></label><label class="wide">対象<input name="target_<?=e($code)?>" value="<?=e((string)($s['target_scope']??''))?>" placeholder="敵単体 / 敵2名 / 敵全体"></label></div></div><?php endforeach;?></div>
<label>修正メモ<input name="metric_note" value="<?=e((string)($r['metric_note']??''))?>" style="width:100%;padding:8px"></label><div class="savebar"><button>この戦法を保存</button></div></div></form><?php endforeach;?><?php endif;?></main></body></html>
