"use strict";
(() => {
const C=window.MobunagaConsult,$=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const version=document.documentElement.dataset.version;
const url=path=>path+"?v="+encodeURIComponent(version);
function storedSeason(){try{return Number(localStorage.getItem("mobunagaSeason"));}catch{return 0;}}
const requested=Number(new URLSearchParams(location.search).get("season"));
const initial=[1,2,3,4].includes(requested)?requested:([1,2,3,4].includes(storedSeason())?storedSeason():4);
const state={season:initial,purpose:"",step:"purpose",furthest:0,level:null,general:"",generals:[],enemies:[],counters:[],excluded:[],family:"",query:"",enemyQuery:"",enemyTier:"",match:"all"};
let catalog,base,s4,allGenerals=[],templates=[],counts=new Map(),generalMap=new Map(),index;
const labels={purpose:"目的",level:"土地レベル",enemies:"メタしたいテンプレート",general:"使いたい武将",exclude:"その他の武将を引き算",counter:"したい対策",results:"編成一覧"};
const purposeLabels={land:"土地攻略",pvp:"対人戦",meta:"対人メタ戦"};
const tips={
oohouritsuru:"役割：味方への通常攻撃を火力に変える。吉川広家を受け役にする案は検証候補です。狙われる手段と回復・軽減を用意し、実際の被害を確認してください。鶴の条件は味方が通常攻撃を「受ける」ことです。",
kikkawahiroie:"役割：大祝鶴と組ませる受け役を検討。自己回復を活かす案ですが、誰が攻撃を引き受けるか、残る1枠が何を補うかを確認します。この組み合わせの低兵損実績は未検証です。効果文が未収録の場合は、ゲーム内の現行効果を確認してください。",
uesugikenshin:"役割：味方の手数を溜めの機会につなげる。相方の採用件数に加え、行動順と通常攻撃が止まる場面を確認します。混乱耐性は謙信本人への効果として考え、部隊全体の対策と分けます。",
kakizakikageie:"役割：突撃火力と無策。相方には攻撃機会を支える働きを求めます。連撃・行動順・制御耐性の条件を確認し、止まったときに他の2人が果たす役割まで比較します。"
};
async function getJSON(path){const r=await fetch(url(path),{cache:"no-cache"});if(!r.ok)throw Error("HTTP "+r.status);return r.json();}
async function liveOrBase(name){const r=await fetch(url("../assets/"+name+".live.json"),{cache:"no-cache"});if(r.ok)return r.json();if(r.status!==404)throw Error("HTTP "+r.status);return getJSON("../assets/"+name+".json");}
function image(g){const p=g?.portrait;return typeof p==="string"&&/^assets\/portraits\/[a-z0-9_-]+\.webp$/.test(p)?'<img class="portrait" src="'+esc(url("../"+p))+'" alt="" loading="lazy">':'<span class="portrait portrait-fallback" aria-hidden="true">将</span>';}
function sourceLink(href,text){const safe=C.safeLink(href);return safe?'<a href="'+esc(safe)+'" target="_blank" rel="noopener">'+esc(text)+'</a>':esc(text);}
function formationHTML(f,open=false){
 const members=f.members.map(m=>'<div class="soldier">'+image(generalMap.get(m.general_id))+'<div><span>'+esc(m.role)+'</span><strong>'+esc(m.general_name)+'</strong></div></div>').join("");
 const body=f.members.map(m=>'<section><h4>'+esc(m.general_name)+'</h4><dl><dt>戦法</dt><dd>'+m.tactics.map(t=>esc(t.tactic_name)).join(" / ")+'</dd><dt>能力振り</dt><dd>'+esc(m.attribute_plan||"記載なし")+'</dd><dt>主兵学</dt><dd>'+esc(m.main_school||"記載なし")+'</dd><dt>副兵学</dt><dd>'+esc(m.sub_school||"記載なし")+'</dd></dl></section>').join("");
 return '<details class="formation"'+(open?' open':'')+'><summary><div class="formation-title"><span class="tag">'+esc(f.tier||"評価未収録")+'</span><b>'+esc(f.troops?.replaceAll(",","・")||"兵種未指定")+'</b><small>'+esc(f.id)+(f.cost?' / COST '+esc(f.cost):'')+'</small></div><div class="team-row">'+members+'</div></summary><div class="formation-body"><div class="member-grid">'+body+'</div>'+((f.requirement||f.template_notes)?'<div class="source-note"><b>掲載条件・代替案</b>'+esc([f.requirement,f.template_notes].filter(Boolean).join("\n"))+'</div>':'')+'<p class="source-link">'+sourceLink(f.source?.source_url,"出典の編成表 "+(f.source_index||"")+" を確認")+'</p><p class="fine">Tierは出典の掲載評価。表記を保持しているため、戦法名に表記揺れが含まれる場合があります。</p></div></details>';
}
function reset(purpose=""){advisorUI.clearPreview();Object.assign(state,{purpose,step:"purpose",furthest:0,level:null,general:"",generals:[],enemies:[],counters:[],excluded:[],family:"",query:"",enemyQuery:"",enemyTier:"",match:"all"});}
function route(){return state.purpose?C.steps(state.purpose):["purpose"];}
function invalidate(){state.furthest=route().indexOf(state.step);}
function go(step){state.step=step;state.furthest=Math.max(state.furthest,route().indexOf(step));render();$("step-title").focus();}
function summary(step){switch(step){case "purpose":return purposeLabels[state.purpose]||"選択してください";case "level":return state.level?"土地 "+state.level:"未選択";case "general":return state.generals.map(id=>generalMap.get(id)?.name).join("・")||"未選択";case "enemies":return state.enemies.length?state.enemies.length+"編成を選択":"複数選択できます";case "counter":return state.counters.length?state.counters.map(k=>C.COUNTERS[k].label).join("・"):"対策を指定せず比較";case "exclude":return state.excluded.length+"名を除外";default:return "条件に合う候補を比較";}}
function allowedNext(){if(state.step==="purpose")return !!state.purpose;if(state.step==="level")return !!state.level;if(state.step==="general")return state.generals.length>0;if(state.step==="enemies")return state.enemies.length>0;return true;}
function refreshSeason(){
 allGenerals=catalog.generals.filter(g=>C.firstSeason(g)<=state.season);generalMap=new Map(allGenerals.map(g=>[g.id,g]));
 templates=C.templatesForSeason(base,s4,state.season).filter(f=>f.members.every(m=>generalMap.has(m.general_id)));
 counts=C.popularity(allGenerals,templates);index=C.evidenceIndex(catalog,state.season);
 $("source-count").textContent="S"+state.season+" · "+templates.length+"編成";
 $("source-link").href=state.season===4?s4.meta.source_url:"https://www.sanguo-zhi.com/entry/s"+state.season+"-template/";
 $("data-summary").textContent="武将"+allGenerals.length+"名 / "+new Set(allGenerals.map(C.family)).size+"家門 · 採用件数はS"+state.season+"の掲載表のみ";
 document.querySelectorAll('a.brand,.header-tools>a').forEach(a=>a.href="../?season="+state.season);
 render();
}
function visibleGenerals(){const q=state.query.normalize("NFKC").trim().toLowerCase();return C.rank(allGenerals,templates).filter(g=>(!state.family||C.family(g)===state.family)&&(!q||(g.name+" "+(g.kana||"")).normalize("NFKC").toLowerCase().includes(q)));}
function filters(){return '<div class="roster-filters"><div class="field"><label for="family">家門を選択</label><select id="family"><option value="">全家門</option>'+[...new Set(allGenerals.map(C.family))].sort((a,b)=>a.localeCompare(b,"ja")).map(f=>'<option'+(state.family===f?' selected':'')+' value="'+esc(f)+'">'+esc(f)+'</option>').join("")+'</select></div><div class="field"><label for="query">武将名で検索</label><input type="search" id="query" value="'+esc(state.query)+'" placeholder="武将名・ふりがな" autocomplete="off"></div></div>';}
function rosterHTML(exclude=false){const visible=visibleGenerals();const related=C.eligible(templates,state.generals);const pairs=C.popularity(allGenerals,related);
 return '<div class="roster-heading"><b>人気順</b><span>'+visible.length+' / '+allGenerals.length+'名</span></div><p class="fine">S'+state.season+'のテンプレート採用件数順。0件の武将も選べます。</p><div class="roster flow-roster">'+(visible.length?visible.map(g=>{
 const pinned=exclude&&state.generals.includes(g.id),removed=state.excluded.includes(g.id);
 return '<button class="general-button'+(removed?' excluded':'')+'" '+(exclude?'data-exclude':'data-general')+'="'+esc(g.id)+'" aria-pressed="'+(exclude?removed:state.generals.includes(g.id))+'"'+(pinned||(!exclude&&state.generals.length===3&&!state.generals.includes(g.id))?' disabled':'')+'>'+image(g)+'<span><b>'+esc(g.name)+'</b><small>'+esc(C.family(g))+' / COST '+esc(g.cost??"—")+'</small>'+(exclude?'<small>'+(pinned?'軸に固定':removed?'除外中・押すと戻す':'候補に残す・押すと除外')+' / 同時採用 '+(pairs.get(g.id)||0)+'件</small>':'')+'</span><span class="count">'+(counts.get(g.id)||0)+'<small>件</small></span></button>';
 }).join(""):'<p class="empty">該当する武将がいません。家門か検索条件を変更してください。</p>')+'</div>';
}
function selectedGeneral(){return '<div class="selection-heading"><b>使いたい武将：'+state.generals.length+' / 3人</b><span class="fine">1人・2人・3人、どこまで選んでも進めます</span></div><p class="fine">最初に選んだ武将が仮大将です。空き枠は次の診断で推薦から選べます。選択済みの武将を押すと解除します。</p><div class="general-slots">'+[0,1,2].map(i=>{const g=generalMap.get(state.generals[i]);return g?'<button class="small-button selected-slot" data-unpin="'+esc(g.id)+'">'+image(g)+'<span>'+esc(g.name)+'<small>'+(i===0?'仮大将':'副将')+' / 解除 ×</small></span></button>':'<div class="empty-slot"><b>'+ (i+1)+'人目：未選択</b><small>今選ぶ／後で推薦から選ぶ</small></div>';}).join('')+'</div>'+(state.generals.length?'<p class="fine">'+state.generals.length+'人を固定 / 同時採用 '+C.eligible(templates,state.generals).length+'編成'+(state.generals.length===3?' / 3人の装備込みで診断します':'')+'</p>':'');}
function allExcluded(){return [...new Set([...state.excluded,...advisorUI.unowned()])].filter(id=>!state.generals.includes(id));}

function exclusions(){return '<div class="selection-summary"><b>残り '+C.eligible(templates,state.generals,allExcluded()).length+'編成</b><span>除外 '+state.excluded.length+'名</span><button class="small-button" data-clear-excluded'+(!state.excluded.length?' disabled':'')+'>除外をすべて戻す</button></div><div class="partner-list">'+state.excluded.map(id=>'<button data-exclude="'+esc(id)+'">'+esc(generalMap.get(id)?.name)+' を戻す</button>').join("")+'</div>';}
function enemyPicker(){const q=state.enemyQuery.normalize("NFKC").trim().toLowerCase();const visible=[...templates].sort((a,b)=>C.tier(a)-C.tier(b)).filter(f=>(!state.enemyTier||f.tier===state.enemyTier)&&(!q||[f.name,f.troops,...f.members.flatMap(m=>[m.general_name,...m.tactics.map(t=>t.tactic_name)])].join(" ").normalize("NFKC").toLowerCase().includes(q)));
 return '<p class="fine">相手にしたい掲載案を1件以上選んでください。同じ三人でも戦法が異なる案は別に選べます。</p><div class="selection-summary"><b>'+state.enemies.length+'編成を選択</b><button class="small-button" data-clear-enemies'+(!state.enemies.length?' disabled':'')+'>選択を解除</button></div><div class="partner-list">'+state.enemies.map(id=>{const f=templates.find(f=>f.id===id);return '<button data-enemy="'+esc(id)+'">'+esc(f.name)+' / '+esc(f.id)+' ×</button>';}).join("")+'</div><div class="roster-filters"><div class="field"><label for="enemy-query">相手の武将・戦法・兵種</label><input id="enemy-query" type="search" value="'+esc(state.enemyQuery)+'" placeholder="武田信玄、混乱など"></div><div class="field"><label for="enemy-tier">掲載Tier</label><select id="enemy-tier"><option value="">すべて</option>'+[...new Set(templates.map(f=>f.tier))].map(t=>'<option value="'+esc(t)+'"'+(state.enemyTier===t?' selected':'')+'>'+esc(t)+'</option>').join("")+'</select></div></div><p class="fine">'+visible.length+'件 / 全'+templates.length+'件</p><div class="enemy-list">'+visible.map(f=>'<div class="enemy-option"><label class="enemy-check"><input type="checkbox" data-enemy-check="'+esc(f.id)+'"'+(state.enemies.includes(f.id)?' checked':'')+'>このテンプレートを対策する</label>'+formationHTML(f)+'</div>').join("")+(visible.length?'':'<p class="empty">条件に合うテンプレートがありません。</p>')+'</div>';
}
function enemyOverview(){if(state.purpose!=="meta")return "";return '<details class="guide"><summary>選んだ相手の戦法・対策の着眼点（'+state.enemies.length+'編成）</summary>'+state.enemies.map(id=>{const f=templates.find(f=>f.id===id),e=C.formationEvidence(f,index);const needs=Object.keys(C.COUNTERS).filter(k=>e.threats[k].length);return formationHTML(f)+'<p class="fine">着眼点：'+(needs.length?needs.map(k=>esc(C.COUNTERS[k].label)).join(" / "):"効果データからの着眼点は未登録")+'。耐性・対象・行動順は個別確認。</p>';}).join("")+'</details>';}
function counterPicker(){const enemies=state.enemies.map(id=>C.formationEvidence(templates.find(f=>f.id===id),index));return selectedGeneral()+enemyOverview()+'<p class="fine">対策を複数選べます。指定しない場合は、軸の武将を含む掲載編成をすべて比較します。</p><div class="counter-choices">'+Object.entries(C.COUNTERS).map(([k,v])=>{const n=enemies.filter(e=>e.threats[k].length).length;return '<label class="brief counter-choice"><input type="checkbox" data-counter="'+k+'"'+(state.counters.includes(k)?' checked':'')+'><span><b>'+esc(v.label)+'</b><small>'+esc(v.detail)+'</small>'+(n?'<small>選んだ相手 '+n+' / '+enemies.length+'編成に関連する効果あり</small>':'')+'</span></label>';}).join("")+'</div><div class="field"><label for="match">複数選んだ場合</label><select id="match"><option value="all"'+(state.match==="all"?' selected':'')+'>すべての対策に手段がある編成</option><option value="any"'+(state.match==="any"?' selected':'')+'>いずれかの対策に手段がある編成</option></select></div><p class="fine">判定対象は掲載戦法・固有戦法・確認済みの無凸特性です。本人限定や確率発動も含むため、候補の根拠で対象・条件を確認してください。</p>';}
function evidenceHTML(record,keys){return keys.map(k=>{const rows=record.evidence.supports[k];return '<section class="evidence-group"><h4>'+esc(C.COUNTERS[k].label)+'：'+(rows.length?'検討できる手段あり':'確認済みの手段なし')+'</h4>'+rows.map(e=>'<details><summary>'+esc(e.owner+' / '+e.name+'（'+e.kind+'）')+'</summary><p class="effect">'+esc(e.effect)+'</p><p class="source-link">'+sourceLink(e.source,"効果の出典")+'</p></details>').join("")+'</section>';}).join("");}
function matchupHTML(record){if(!record.coverage.length)return "";return '<details class="evidence"><summary>相手'+record.coverage.length+'編成との照合（手段・未確認）</summary><div class="matchups"><h4>選んだ相手ごとの確認</h4>'+record.coverage.map(c=>'<section class="matchup"><b>'+esc(c.enemy.formation.name)+'</b><small>'+esc(c.enemy.formation.id)+'</small>'+(c.needs.length?'<p>対策の着眼点：'+c.needs.map(k=>esc(C.COUNTERS[k].label)).join(" / ")+'</p><p>自軍の手段：'+(c.matched.length?c.matched.map(k=>esc(C.COUNTERS[k].label)).join(" / "):"確認済みの手段なし")+'</p>':'<p>この相手の対策情報は未登録です。</p>')+'<details><summary>相手側の根拠・未確認部分</summary>'+c.needs.map(k=>'<p><b>'+esc(C.COUNTERS[k].label)+'</b></p>'+c.enemy.evidence.threats[k].map(e=>'<p class="effect">'+esc(e.owner+' / '+e.name)+'：'+esc(e.effect)+'</p>').join("")).join("")+'<p class="fine">相手側の効果文未収録 '+c.enemy.evidence.missing+'件。兵種・速度・対象への命中・耐性・発動順による成否は未判定です。</p></details></section>').join("")+'<p class="fine">手段の存在を比較しています。相手に勝てる判定や、全員を守れる保証ではありません。</p></div></details>';}
function landGuide(){if(state.purpose!=="land")return "";const link=state.season===4&&[4,5,6].includes(state.level)?'<a href="../s4-startdash/land'+state.level+'/?season=4">土地'+state.level+'の守備隊・攻略資料を確認</a>':"このシーズン・土地レベルの攻略資料との自動照合は未対応です。";return '<div class="brief"><small>S'+state.season+' / 土地'+state.level+'</small><h3>出撃前に守備隊と照合</h3><p>'+link+'</p><p class="fine">以下は武将条件に合う掲載テンプレートです。土地'+state.level+'での勝率・兵損・必要兵力は未判定です。'+(state.level>=7?'初戦後の残兵力と、続く守備隊への対応も確認してください。':'相手の兵種、武将レベル、戦法レベル、士気をそろえて戦報と比較してください。')+'</p></div>';}
function resultsHTML(){const result=C.candidates(templates,{...state,excluded:allExcluded()},index);const total=C.eligible(templates,state.generals).length;const available=C.eligible(templates,state.generals,allExcluded()).length;const g=generalMap.get(state.general);
 return selectedGeneral()+'<div id="advisor-root"></div>'+landGuide()+enemyOverview()+'<div class="section-heading"><h3>条件に合う編成 '+result.length+'件</h3><button class="small-button" data-go="'+(state.purpose==="land"?'exclude':'counter')+'">条件を変更</button></div><p class="fine">軸の武将を採用 '+total+'件 → 武将の除外後 '+available+'件 → 対策条件 '+result.length+'件。'+(state.purpose==="meta"?'選択した対策の一致数、相手の着眼点に手段がある編成数、掲載Tierの順。':'掲載Tier順。')+'同じ三人でも掲載案ごとに表示します。</p>'+
 (result.length?result.map((r,i)=>'<article class="candidate">'+formationHTML(r.formation,i===0)+'<button class="small-button" data-assess-template="'+esc(r.formation.id)+'">この掲載戦法で3人を診断</button>'+(state.purpose!=="land"?'<details class="evidence"><summary>対策の根拠と対象・成立条件</summary>'+evidenceHTML(r,state.counters.length?state.counters:Object.keys(C.COUNTERS).filter(k=>r.evidence.supports[k].length))+'<p class="fine">効果文未収録 '+r.evidence.missing+'件。未登録の手段は判定に含めていません。装備戦法の所持、対象、発動率、ターン制限、凸条件を確認してください。</p></details>'+matchupHTML(r):'')+'</article>').join(""):'<div class="empty"><b>条件に合う掲載編成は0件です</b><p>'+(total===0?'固定した武将すべてを含むテンプレートは未収録です。上の推薦で組み合わせを検討できます。':available===0?'除外した武将を戻すと、候補が増えます。':'指定した対策の手段を確認できる編成がありません。対策を減らすか「いずれか」に変更してください。')+'</p><button class="small-button" data-go="general">軸の武将を選び直す</button> '+(state.excluded.length?'<button class="small-button" data-clear-excluded>除外をすべて戻す</button>':'')+(state.counters.length?'<button class="small-button" data-clear-counters>対策指定を外して比較する</button>':'')+'</div>')+
 '<details class="guide"><summary>'+esc(g.name)+'の固有戦法を確認</summary><p><b>'+esc(g.unique_tactic?.name||"未収録")+'</b></p><p class="effect">'+esc(g.unique_tactic?.effect||"効果文は未収録です。")+'</p><a href="../?open=generals&amp;id='+encodeURIComponent(g.id)+'&amp;season='+state.season+'#generals">武将録で特性・凸条件を確認</a></details><aside class="tips"><header><img src="../assets/mobunaga.png" alt="" loading="lazy"><div><h3>モブナガ TIPS</h3><small>役割と相性の検討案</small></div></header><p>'+esc(tips[g.id]||"軸の武将を固定して、残る二人が補う回復・制御・行動順・兵種を確認します。対策手段があっても、対象が本人だけなら他の二人は守れません。掲載条件と自軍の育成状況を照合してください。")+'</p></aside>';
}
function render(focusId){
 const focus=focusId?$(focusId):null,pos=focus?.selectionStart;
 document.querySelectorAll("[data-purpose]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.purpose===state.purpose)));
 $("context").textContent="S"+state.season+" / "+(purposeLabels[state.purpose]||"目的を選択")+(state.purpose==="land"&&state.level?' / 土地'+state.level:'');
 $("step-title").textContent=labels[state.step];
 const path=route(),current=path.indexOf(state.step);
 $("flow").innerHTML=path.map((step,i)=>'<div class="flow-node"><button data-go="'+step+'"'+(i>state.furthest?' disabled':'')+(step===state.step?' aria-current="step"':'')+'><i>'+String(i+1).padStart(2,"0")+'</i><span><b>'+labels[step]+'</b><small>'+esc(i<=state.furthest?summary(step):"未選択")+'</small></span></button></div>').join("");
 let html="";
 if(state.step==="purpose")html='<div class="brief"><h3>上の三つから目的を選んでください</h3><p>目的に合わせて、必要な条件を順番に伺います。</p></div>';
 if(state.step==="level")html='<p class="fine">攻略する土地レベルを選んでください。</p><div class="levels">'+[4,5,6,7,8].map(n=>'<button data-level="'+n+'" aria-pressed="'+(state.level===n)+'">'+n+'</button>').join("")+'<p class="fine">土地攻略資料への案内と、出撃前の確認項目が切り替わります。</p>';
 if(state.step==="enemies")html=enemyPicker();
 if(state.step==="general")html='<div id="selected-general">'+selectedGeneral()+'</div>'+filters()+'<div id="roster-content">'+rosterHTML()+'</div>';
 if(state.step==="exclude")html=selectedGeneral()+'<p class="fine">最初は全武将を候補に残しています。未所持・他部隊で使用中など、使わない武将を押して外してください。もう一度押すと戻せます。軸の武将は固定です。</p><div id="exclusion-summary">'+exclusions()+'</div>'+filters()+'<div id="roster-content">'+rosterHTML(true)+'</div>';
 if(state.step==="counter")html=counterPicker();
 if(state.step==="results")html=resultsHTML();
 $("step-content").innerHTML=html;if(state.step==="results")advisorUI.mount($("advisor-root"),{state,catalog,index,templates,generals:allGenerals,excluded:allExcluded(),onChange:()=>render(),onLeader:id=>{if(!state.generals.includes(id))return;state.generals=[id,...state.generals.filter(x=>x!==id)];state.general=id;render();},onPin:id=>{if(state.generals.length<3&&!state.generals.includes(id)){state.generals.push(id);state.general=state.generals[0];render();}}});
 $("flow-actions").innerHTML=(current>0?'<button class="small-button" data-back>前へ戻る</button>':'')+(current<path.length-1&&state.step!=="purpose"?'<button class="small-button next" data-next'+(!allowedNext()?' disabled':'')+'>'+((path[current+1]==="results")?'編成一覧を見る':'次へ：'+labels[path[current+1]])+'</button>':'');
 if(focusId&&$(focusId)){const el=$(focusId);el.focus();if(typeof pos==="number"&&el.type==="search")el.setSelectionRange(pos,pos);}
}
function updateRoster(){const el=$("roster-content");if(el)el.innerHTML=rosterHTML(state.step==="exclude");}
function toggle(list,value){return list.includes(value)?list.filter(x=>x!==value):[...list,value];}
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b||!catalog||b.disabled)return;
 if(b.dataset.assessTemplate){advisorUI.useTemplate(templates.find(f=>f.id===b.dataset.assessTemplate));return;}
 if(b.dataset.purpose){reset(b.dataset.purpose);go(route()[1]);return;}
 if(b.id==="restart"){reset();go("purpose");return;}
 if(b.hasAttribute("data-next")){if(allowedNext()){state.family="";state.query="";go(route()[route().indexOf(state.step)+1]);}return;}
 if(b.hasAttribute("data-back")){go(route()[route().indexOf(state.step)-1]);return;}
 if(b.dataset.go){if(route().indexOf(b.dataset.go)<=state.furthest)go(b.dataset.go);return;}
 if(b.dataset.level){const n=Number(b.dataset.level);if(state.level!==n){state.level=n;invalidate();}render();return;}
 if(b.dataset.general||b.dataset.unpin){const id=b.dataset.general||b.dataset.unpin;if(!state.generals.includes(id)&&state.generals.length>=3)return;state.generals=toggle(state.generals,id);state.general=state.generals[0]||'';state.excluded=state.excluded.filter(x=>!state.generals.includes(x));advisorUI.clearPreview();if(state.step==='results'&&!state.generals.length){state.step='general';invalidate();go('general');return;}if(state.step!=='results')invalidate();const scroll=document.querySelector('.flow-roster')?.scrollTop||0;render();if(document.querySelector('.flow-roster'))document.querySelector('.flow-roster').scrollTop=scroll;return;}
 if(b.dataset.exclude){if(state.generals.includes(b.dataset.exclude))return;state.excluded=toggle(state.excluded,b.dataset.exclude);if(state.step==="exclude"){invalidate();const sc=document.querySelector('.flow-roster').scrollTop;updateRoster();$("exclusion-summary").innerHTML=exclusions();document.querySelector('.flow-roster').scrollTop=sc;document.querySelector('[data-exclude="'+b.dataset.exclude+'"]')?.focus({preventScroll:true});$("announcement").textContent='残り '+C.eligible(templates,state.generals,allExcluded()).length+'編成';document.querySelector('#flow [data-go="exclude"] small').textContent=summary('exclude');document.querySelector('#flow [data-go="results"]').disabled=true;}else render();return;}
 if(b.dataset.enemy){state.enemies=toggle(state.enemies,b.dataset.enemy);state.counters=[];invalidate();render();return;}
 if(b.hasAttribute("data-clear-excluded")){state.excluded=[];render();return;}
 if(b.hasAttribute("data-clear-enemies")){state.enemies=[];state.counters=[];invalidate();render();return;}
 if(b.hasAttribute("data-clear-counters")){state.counters=[];render();}
});
document.addEventListener("change",e=>{const el=e.target;if(el.id==="season"){state.season=Number(el.value);try{localStorage.setItem("mobunagaSeason",String(state.season));}catch{}document.cookie="mobunaga_season="+state.season+"; Path=/; Max-Age=31536000; SameSite=Lax"+(location.protocol==="https:"?"; Secure":"");const u=new URL(location.href);u.searchParams.set("season",String(state.season));history.replaceState(null,"",u);reset();if(catalog)refreshSeason();return;}
 if(!catalog)return;
 if(el.id==="family"){state.family=el.value;updateRoster();}
 if(el.id==="enemy-tier"){state.enemyTier=el.value;render("enemy-tier");}
 if(el.dataset.enemyCheck){state.enemies=toggle(state.enemies,el.dataset.enemyCheck);state.counters=[];invalidate();const sc=document.querySelector('.enemy-list').scrollTop;render();document.querySelector('.enemy-list').scrollTop=sc;document.querySelector('[data-enemy-check="'+el.dataset.enemyCheck+'"]').focus({preventScroll:true});}
 if(el.dataset.counter){state.counters=toggle(state.counters,el.dataset.counter);invalidate();render();document.querySelector('[data-counter="'+el.dataset.counter+'"]').focus({preventScroll:true});}
 if(el.id==="match"){state.match=el.value;invalidate();render("match");}
});
document.addEventListener("input",e=>{if(!catalog)return;if(e.target.id==="query"){state.query=e.target.value;updateRoster();}if(e.target.id==="enemy-query"){state.enemyQuery=e.target.value;render("enemy-query");}});
const advisorUI=window.MobunagaAdvisorUI({esc,image,sourceLink});
$("season").value=String(state.season);
document.addEventListener("error",e=>{const img=e.target;if(img?.matches?.("img.portrait")){const fallback=document.createElement("span");fallback.className="portrait portrait-fallback";fallback.setAttribute("aria-hidden","true");fallback.textContent="将";img.replaceWith(fallback);}},true);
(async()=>{try{const result=await Promise.all([liveOrBase("database"),liveOrBase("formations"),getJSON("../assets/s4-additions.json"),getJSON("../assets/s4-templates.json")]);if(!Array.isArray(result[0].generals)||!Array.isArray(result[1].formations)||!Array.isArray(result[3].formations))throw Error("Invalid catalog");catalog=C.catalog(result[0],result[2],result[1]);base=result[1];s4=result[3];refreshSeason();$("workspace").hidden=false;$("load-status").hidden=true;}catch(error){$("load-status").textContent="資料を読み込めませんでした。通信状態を確認して再読み込みしてください。";const retry=document.createElement("button");retry.className="small-button";retry.textContent="再読み込み";retry.addEventListener("click",()=>location.reload());$("load-status").append(" ",retry);console.error("Formation consultation load failed",error);}})();
})();
