<?php
declare(strict_types=1);
if (!defined('MOBUNAGA_ANALYSIS_ROOM')) { http_response_code(404); exit; }

/**
 * 2026-10-07 05:39:41 録画（6分03秒）から抽出・目視照合した凸数。
 *
 * - カード下部の赤い菱形だけを凸として数える。
 * - 黄色い菱形は0凸。
 * - 同じプレイヤーは1人1件にまとめる。
 * - 0凸も確認済み値として保持するが、比較画面では表示しない。
 * - 推測値は入れない。
 *
 * 八雲: 27名 / 合計145凸
 * 傾奇集団: 27名（うち0凸1名） / 正の凸合計140凸
 */
function battleReviewedLimitBreakObservations20261007(): array
{
    return [
        [
            'limit_break_observation_id'=>'20261007-video-own-01',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'桶塚悠衣','own_limit_break_total'=>5,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-02',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'三浦按針','own_limit_break_total'=>2,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-03',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'伏黒甚爾','own_limit_break_total'=>6,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-04',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'あお丸','own_limit_break_total'=>4,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-05',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'ありぃ','own_limit_break_total'=>1,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-06',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'ちー','own_limit_break_total'=>4,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-07',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'カナブン','own_limit_break_total'=>8,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-08',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'レヴィ','own_limit_break_total'=>9,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-09',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'闇の土鬼','own_limit_break_total'=>13,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-10',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'相馬鑑載','own_limit_break_total'=>1,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-11',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'鮎田トト','own_limit_break_total'=>9,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-12',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'丸康秀','own_limit_break_total'=>7,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-13',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'入田信方','own_limit_break_total'=>2,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-14',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'豊原夏月','own_limit_break_total'=>1,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-15',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'愚地独歩','own_limit_break_total'=>4,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-16',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'shin','own_limit_break_total'=>3,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-17',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'黒田忠兵衛','own_limit_break_total'=>1,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-18',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'パタコ','own_limit_break_total'=>5,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-19',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'ニケ','own_limit_break_total'=>1,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-20',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'ぽんすけ','own_limit_break_total'=>8,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-21',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'ノエル','own_limit_break_total'=>13,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-22',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'Y','own_limit_break_total'=>5,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-23',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'武藤元康','own_limit_break_total'=>9,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-24',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'ニコ','own_limit_break_total'=>10,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-25',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'二東三文','own_limit_break_total'=>1,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-26',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'丑能','own_limit_break_total'=>2,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-own-27',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'own_name'=>'ヤーコポ','own_limit_break_total'=>11,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-01',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'kuros','enemy_limit_break_total'=>8,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-02',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'春日虎綱','enemy_limit_break_total'=>6,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-03',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'中村耕太郎','enemy_limit_break_total'=>15,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-04',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'とみけん','enemy_limit_break_total'=>7,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-05',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'色即是空','enemy_limit_break_total'=>2,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-06',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'ぷにるんず','enemy_limit_break_total'=>1,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-07',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'あるきめです','enemy_limit_break_total'=>10,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-08',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'愛羅','enemy_limit_break_total'=>2,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-09',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'中ノ村博史','enemy_limit_break_total'=>2,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-10',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'ヤタガラス','enemy_limit_break_total'=>2,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-11',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'・・秀島・・','enemy_limit_break_total'=>7,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-12',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'キンカズ','enemy_limit_break_total'=>1,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-13',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'山神海太郎','enemy_limit_break_total'=>14,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-14',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'中尊孔明','enemy_limit_break_total'=>3,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-15',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'テテ','enemy_limit_break_total'=>1,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-16',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'堀尾長房','enemy_limit_break_total'=>2,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-17',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'坂田銀時','enemy_limit_break_total'=>11,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-18',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'百花繚乱','enemy_limit_break_total'=>4,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-19',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'濃姫','enemy_limit_break_total'=>2,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-20',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'穂和斎麻呂','enemy_limit_break_total'=>8,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-21',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'ぽこたんイン','enemy_limit_break_total'=>3,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-22',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'天鳥道虫','enemy_limit_break_total'=>2,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-23',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'百式','enemy_limit_break_total'=>1,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-24',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'未登録','enemy_limit_break_total'=>2,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-25',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'松平信康','enemy_limit_break_total'=>9,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-26',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'功','enemy_limit_break_total'=>15,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ],
        [
            'limit_break_observation_id'=>'20261007-video-enemy-27',
            'season'=>'S4','limit_breaks_only'=>true,'limit_break_roster'=>true,
            'enemy_name'=>'よ','enemy_limit_break_total'=>0,
            'limit_breaks_review'=>'visual_limit_break_review',
            'source_note'=>'レコーディング 2026-10-07 053941.mp4 全体確認',
        ]
    ];
}
